### ISSUE TITLE
looking forward to see more documentations about this project :)

### ISSUE THREAD

**Issue by xieyuheng** [trans/fulang#1]
:)

**Comment by xieyuheng** [comment]
I am willing to write Chinese version of the doc.
is it wished ? any guides to me ?

**Comment by xieyuheng** [comment]
and, maybe I can play with this language in the programming language I am designing :)

**Comment by xieyuheng** [comment]
I recommend "福語" as the Chinese name of your lang.
"福" means "blessing", "語" means "language"

**Comment by trans** [comment]
Sorry I haven't gotten back to you sooner. I have been giving this project some serious thought, but haven't nailed it down yet. I am glad you find this project interesting. It is however still very much in the early stages. In fact one of my original ideas turned out to be not so good, so I had to go back to the drawing board on that. Right now I am just flushing out the possibilities.

**Comment by trans** [comment]
> I recommend "福語" as the Chinese name of your lang. "福" means "blessing", "語" means "language"

I like it actually. How is that pronounced phonetically?

**Comment by xieyuheng** [comment]
"fu" for "福" : http://ctext.org/dictionary.pl?if=en&char=%E7%A6%8F
